### PR TITLE
add disabled_stacks

### PR DESCRIPTION
**Pull request by friedenberg**
cc @jgedarovich and @mrtazz

### CODE REVIEW

**Comment by jayson** [comment]
Looks pretty good to me, do you still need a merge on this?

**Comment by friedenberg** [comment]
Hey yeah, I think we'd still like to have this functionality. @jgedarovich, thoughts?

**Comment by jgedarovich** [comment]
awesome! have you tested it out on your vm? I'd love to see what it looks like

**Comment by jgedarovich** [comment]
lgtm, shibbit

**Comment by friedenberg** [comment]
looks like this looks good to everyone. Can we merge?

**Pull request merged**
